-- Events with Nick v7 secure production database schema
-- Run this in Supabase SQL Editor before uploading the v7 files to GitHub Pages.
-- This version protects the owner portal with Supabase Auth + Row Level Security.
-- Public visitors can submit booking requests, but only approved admins can read/update/delete bookings.

-- 1) Tables
create table if not exists public.bookings (
  id text primary key,
  "dateCreated" timestamptz default now(),
  name text not null,
  phone text not null,
  email text,
  "preferredCommunication" text,
  "altContact" text,
  "eventType" text,
  "eventDate" date,
  guests text,
  location text,
  package text,
  budget text,
  message text,
  status text default 'New',
  priority text default 'Normal',
  notes text,
  "quoteAmount" numeric,
  "assignedTo" text default 'Nick'
);

alter table public.bookings add column if not exists "preferredCommunication" text;
alter table public.bookings add column if not exists "altContact" text;
alter table public.bookings add column if not exists status text default 'New';
alter table public.bookings add column if not exists priority text default 'Normal';
alter table public.bookings add column if not exists notes text;
alter table public.bookings add column if not exists "quoteAmount" numeric;
alter table public.bookings add column if not exists "assignedTo" text default 'Nick';

create table if not exists public.site_settings (
  id text primary key default 'main',
  settings jsonb not null,
  updated_at timestamptz default now()
);

create table if not exists public.quote_pricing (
  id text primary key default 'main',
  pricing jsonb not null,
  updated_at timestamptz default now()
);

create table if not exists public.banking_details (
  id text primary key default 'main',
  banking jsonb not null,
  updated_at timestamptz default now()
);

create table if not exists public.gallery_items (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  image text not null,
  created_at timestamptz default now()
);

-- Admin allow-list. Add Nick's Supabase Auth email here after creating the Auth user.
create table if not exists public.admin_users (
  email text primary key,
  user_id uuid unique,
  display_name text,
  is_active boolean not null default true,
  created_at timestamptz default now()
);

-- 2) RLS helper. The owner of this function can read admin_users to check the logged-in user.
create or replace function public.is_events_with_nick_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users au
    where au.is_active = true
      and (
        au.user_id = auth.uid()
        or lower(au.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
      )
  );
$$;

revoke all on function public.is_events_with_nick_admin() from public;
grant execute on function public.is_events_with_nick_admin() to anon, authenticated;

-- 3) Enable Row Level Security
alter table public.bookings enable row level security;
alter table public.site_settings enable row level security;
alter table public.quote_pricing enable row level security;
alter table public.banking_details enable row level security;
alter table public.gallery_items enable row level security;
alter table public.admin_users enable row level security;

-- 4) Remove older presentation policies before creating secure policies.
drop policy if exists "Public can create bookings" on public.bookings;
drop policy if exists "Owner can read bookings" on public.bookings;
drop policy if exists "Owner can update bookings" on public.bookings;
drop policy if exists "Owner can delete bookings" on public.bookings;
drop policy if exists "Admin can read bookings" on public.bookings;
drop policy if exists "Admin can update bookings" on public.bookings;
drop policy if exists "Admin can delete bookings" on public.bookings;

drop policy if exists "Public can read site settings" on public.site_settings;
drop policy if exists "Presentation can insert site settings" on public.site_settings;
drop policy if exists "Presentation can update site settings" on public.site_settings;
drop policy if exists "Admin can insert site settings" on public.site_settings;
drop policy if exists "Admin can update site settings" on public.site_settings;
drop policy if exists "Admin can delete site settings" on public.site_settings;

drop policy if exists "Presentation can read pricing" on public.quote_pricing;
drop policy if exists "Presentation can insert pricing" on public.quote_pricing;
drop policy if exists "Presentation can update pricing" on public.quote_pricing;
drop policy if exists "Admin can read pricing" on public.quote_pricing;
drop policy if exists "Admin can insert pricing" on public.quote_pricing;
drop policy if exists "Admin can update pricing" on public.quote_pricing;
drop policy if exists "Admin can delete pricing" on public.quote_pricing;

drop policy if exists "Presentation can read banking" on public.banking_details;
drop policy if exists "Presentation can insert banking" on public.banking_details;
drop policy if exists "Presentation can update banking" on public.banking_details;
drop policy if exists "Admin can read banking" on public.banking_details;
drop policy if exists "Admin can insert banking" on public.banking_details;
drop policy if exists "Admin can update banking" on public.banking_details;
drop policy if exists "Admin can delete banking" on public.banking_details;

drop policy if exists "Public can read gallery" on public.gallery_items;
drop policy if exists "Presentation can insert gallery" on public.gallery_items;
drop policy if exists "Presentation can delete gallery" on public.gallery_items;
drop policy if exists "Admin can insert gallery" on public.gallery_items;
drop policy if exists "Admin can update gallery" on public.gallery_items;
drop policy if exists "Admin can delete gallery" on public.gallery_items;

drop policy if exists "Admins can read admin users" on public.admin_users;

-- 5) Public booking policy: visitors can submit enquiries only.
create policy "Public can create bookings" on public.bookings
for insert
to anon, authenticated
with check (
  coalesce(status, 'New') = 'New'
  and coalesce(priority, 'Normal') = 'Normal'
  and "quoteAmount" is null
);

-- 6) Admin booking policies: only approved admins can manage bookings.
create policy "Admin can read bookings" on public.bookings
for select
to authenticated
using (public.is_events_with_nick_admin());

create policy "Admin can update bookings" on public.bookings
for update
to authenticated
using (public.is_events_with_nick_admin())
with check (public.is_events_with_nick_admin());

create policy "Admin can delete bookings" on public.bookings
for delete
to authenticated
using (public.is_events_with_nick_admin());

-- 7) Website settings: public can read; only admin can edit.
create policy "Public can read site settings" on public.site_settings
for select
to anon, authenticated
using (true);

create policy "Admin can insert site settings" on public.site_settings
for insert
to authenticated
with check (public.is_events_with_nick_admin());

create policy "Admin can update site settings" on public.site_settings
for update
to authenticated
using (public.is_events_with_nick_admin())
with check (public.is_events_with_nick_admin());

create policy "Admin can delete site settings" on public.site_settings
for delete
to authenticated
using (public.is_events_with_nick_admin());

-- 8) Pricing and banking details: admin only.
create policy "Admin can read pricing" on public.quote_pricing
for select
to authenticated
using (public.is_events_with_nick_admin());

create policy "Admin can insert pricing" on public.quote_pricing
for insert
to authenticated
with check (public.is_events_with_nick_admin());

create policy "Admin can update pricing" on public.quote_pricing
for update
to authenticated
using (public.is_events_with_nick_admin())
with check (public.is_events_with_nick_admin());

create policy "Admin can delete pricing" on public.quote_pricing
for delete
to authenticated
using (public.is_events_with_nick_admin());

create policy "Admin can read banking" on public.banking_details
for select
to authenticated
using (public.is_events_with_nick_admin());

create policy "Admin can insert banking" on public.banking_details
for insert
to authenticated
with check (public.is_events_with_nick_admin());

create policy "Admin can update banking" on public.banking_details
for update
to authenticated
using (public.is_events_with_nick_admin())
with check (public.is_events_with_nick_admin());

create policy "Admin can delete banking" on public.banking_details
for delete
to authenticated
using (public.is_events_with_nick_admin());

-- 9) Gallery: public website can read; only admin can manage.
create policy "Public can read gallery" on public.gallery_items
for select
to anon, authenticated
using (true);

create policy "Admin can insert gallery" on public.gallery_items
for insert
to authenticated
with check (public.is_events_with_nick_admin());

create policy "Admin can update gallery" on public.gallery_items
for update
to authenticated
using (public.is_events_with_nick_admin())
with check (public.is_events_with_nick_admin());

create policy "Admin can delete gallery" on public.gallery_items
for delete
to authenticated
using (public.is_events_with_nick_admin());

-- 10) Admin allow-list visibility. Admin users are maintained from SQL Editor.
create policy "Admins can read admin users" on public.admin_users
for select
to authenticated
using (public.is_events_with_nick_admin());

-- 11) Permissions for Supabase REST API roles.
grant usage on schema public to anon, authenticated;
grant insert on public.bookings to anon, authenticated;
grant select, insert, update, delete on public.bookings to authenticated;
grant select on public.site_settings, public.gallery_items to anon, authenticated;
grant select, insert, update, delete on public.site_settings, public.quote_pricing, public.banking_details, public.gallery_items to authenticated;
grant select on public.admin_users to authenticated;
grant usage, select on sequence public.gallery_items_id_seq to authenticated;

-- AFTER CREATING NICK'S AUTH USER:
-- 1. Go to Authentication -> Users -> Add user.
-- 2. Create Nick's email and password.
-- 3. Run this line, replacing the email with the exact Auth user email:
-- insert into public.admin_users (email, display_name) values ('nick@example.com', 'Nick') on conflict (email) do update set is_active = true, display_name = excluded.display_name;
