-- Events with Nick v7.4 stable secure database schema
-- Run this in Supabase SQL Editor once before uploading the v7.4 files.
-- Public website visitors can submit bookings.
-- Only authenticated admin users created in Supabase Authentication can read/manage admin data.
-- Recommended: in Supabase Authentication settings, keep sign-ups disabled and create Nick's admin user manually.

-- 1) Tables
create table if not exists public.bookings (
  id text primary key,
  "dateCreated" timestamptz default now(),
  name text not null,
  phone text not null,
  email text,
  "preferredCommunication" text,
  "altContact" text,
  "eventType" text,
  "eventDate" date,
  guests text,
  location text,
  package text,
  budget text,
  message text,
  status text default 'New',
  priority text default 'Normal',
  notes text,
  "quoteAmount" numeric,
  "assignedTo" text default 'Nick'
);

alter table public.bookings add column if not exists "preferredCommunication" text;
alter table public.bookings add column if not exists "altContact" text;
alter table public.bookings add column if not exists status text default 'New';
alter table public.bookings add column if not exists priority text default 'Normal';
alter table public.bookings add column if not exists notes text;
alter table public.bookings add column if not exists "quoteAmount" numeric;
alter table public.bookings add column if not exists "assignedTo" text default 'Nick';

create table if not exists public.site_settings (
  id text primary key default 'main',
  settings jsonb not null,
  updated_at timestamptz default now()
);

create table if not exists public.quote_pricing (
  id text primary key default 'main',
  pricing jsonb not null,
  updated_at timestamptz default now()
);

create table if not exists public.banking_details (
  id text primary key default 'main',
  banking jsonb not null,
  updated_at timestamptz default now()
);

create table if not exists public.gallery_items (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  image text not null,
  created_at timestamptz default now()
);

-- Kept only for compatibility with older builds. v7.4 does not depend on this table.
create table if not exists public.admin_users (
  email text primary key,
  user_id uuid unique,
  display_name text,
  is_active boolean not null default true,
  created_at timestamptz default now()
);

-- 2) Enable Row Level Security
alter table public.bookings enable row level security;
alter table public.site_settings enable row level security;
alter table public.quote_pricing enable row level security;
alter table public.banking_details enable row level security;
alter table public.gallery_items enable row level security;
alter table public.admin_users enable row level security;

-- 3) Remove old policies from demo/v7/v7.1/v7.2
-- Bookings
drop policy if exists "Public can create bookings" on public.bookings;
drop policy if exists "Owner can read bookings" on public.bookings;
drop policy if exists "Owner can update bookings" on public.bookings;
drop policy if exists "Owner can delete bookings" on public.bookings;
drop policy if exists "Admin can read bookings" on public.bookings;
drop policy if exists "Admin can insert bookings" on public.bookings;
drop policy if exists "Admin can update bookings" on public.bookings;
drop policy if exists "Admin can delete bookings" on public.bookings;

-- Site settings
drop policy if exists "Public can read site settings" on public.site_settings;
drop policy if exists "Presentation can insert site settings" on public.site_settings;
drop policy if exists "Presentation can update site settings" on public.site_settings;
drop policy if exists "Admin can read site settings" on public.site_settings;
drop policy if exists "Admin can insert site settings" on public.site_settings;
drop policy if exists "Admin can update site settings" on public.site_settings;
drop policy if exists "Admin can delete site settings" on public.site_settings;

-- Pricing
drop policy if exists "Presentation can read pricing" on public.quote_pricing;
drop policy if exists "Presentation can insert pricing" on public.quote_pricing;
drop policy if exists "Presentation can update pricing" on public.quote_pricing;
drop policy if exists "Admin can read pricing" on public.quote_pricing;
drop policy if exists "Public can read pricing" on public.quote_pricing;
drop policy if exists "Admin can insert pricing" on public.quote_pricing;
drop policy if exists "Admin can update pricing" on public.quote_pricing;
drop policy if exists "Admin can delete pricing" on public.quote_pricing;

-- Banking
drop policy if exists "Presentation can read banking" on public.banking_details;
drop policy if exists "Presentation can insert banking" on public.banking_details;
drop policy if exists "Presentation can update banking" on public.banking_details;
drop policy if exists "Admin can read banking" on public.banking_details;
drop policy if exists "Public can read banking" on public.banking_details;
drop policy if exists "Admin can insert banking" on public.banking_details;
drop policy if exists "Admin can update banking" on public.banking_details;
drop policy if exists "Admin can delete banking" on public.banking_details;

-- Gallery
drop policy if exists "Public can read gallery" on public.gallery_items;
drop policy if exists "Presentation can insert gallery" on public.gallery_items;
drop policy if exists "Presentation can delete gallery" on public.gallery_items;
drop policy if exists "Admin can insert gallery" on public.gallery_items;
drop policy if exists "Admin can update gallery" on public.gallery_items;
drop policy if exists "Admin can delete gallery" on public.gallery_items;

-- Admin users compatibility table
drop policy if exists "Admins can read admin users" on public.admin_users;

-- 4) Public website permissions
create policy "Public can create bookings" on public.bookings
for insert
to anon, authenticated
with check (
  coalesce(status, 'New') = 'New'
  and coalesce(priority, 'Normal') = 'Normal'
  and "quoteAmount" is null
);

create policy "Public can read site settings" on public.site_settings
for select
to anon, authenticated
using (true);

create policy "Public can read gallery" on public.gallery_items
for select
to anon, authenticated
using (true);

-- 5) Owner portal permissions
-- Admin access is controlled by Supabase Authentication login.
-- Create Nick's admin user manually in Authentication -> Users.
create policy "Admin can read bookings" on public.bookings
for select
to authenticated
using (auth.role() = 'authenticated');

create policy "Admin can insert bookings" on public.bookings
for insert
to authenticated
with check (auth.role() = 'authenticated');

create policy "Admin can update bookings" on public.bookings
for update
to authenticated
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

create policy "Admin can delete bookings" on public.bookings
for delete
to authenticated
using (auth.role() = 'authenticated');

create policy "Admin can read pricing" on public.quote_pricing
for select
to authenticated
using (auth.role() = 'authenticated');

create policy "Admin can insert pricing" on public.quote_pricing
for insert
to authenticated
with check (auth.role() = 'authenticated');

create policy "Admin can update pricing" on public.quote_pricing
for update
to authenticated
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

create policy "Admin can delete pricing" on public.quote_pricing
for delete
to authenticated
using (auth.role() = 'authenticated');

create policy "Admin can insert site settings" on public.site_settings
for insert
to authenticated
with check (auth.role() = 'authenticated');

create policy "Admin can update site settings" on public.site_settings
for update
to authenticated
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

create policy "Admin can delete site settings" on public.site_settings
for delete
to authenticated
using (auth.role() = 'authenticated');

create policy "Admin can read banking" on public.banking_details
for select
to authenticated
using (auth.role() = 'authenticated');

create policy "Admin can insert banking" on public.banking_details
for insert
to authenticated
with check (auth.role() = 'authenticated');

create policy "Admin can update banking" on public.banking_details
for update
to authenticated
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

create policy "Admin can delete banking" on public.banking_details
for delete
to authenticated
using (auth.role() = 'authenticated');

create policy "Admin can insert gallery" on public.gallery_items
for insert
to authenticated
with check (auth.role() = 'authenticated');

create policy "Admin can update gallery" on public.gallery_items
for update
to authenticated
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

create policy "Admin can delete gallery" on public.gallery_items
for delete
to authenticated
using (auth.role() = 'authenticated');

-- 6) REST API grants
grant usage on schema public to anon, authenticated;
grant insert on public.bookings to anon;
grant select, insert, update, delete on public.bookings to authenticated;
grant select on public.site_settings, public.gallery_items to anon, authenticated;
grant select, insert, update, delete on public.site_settings, public.quote_pricing, public.banking_details, public.gallery_items to authenticated;
grant usage, select on sequence public.gallery_items_id_seq to authenticated;


-- 7) Starter rows for admin settings. These prevent empty Price Settings/Banking tables.
insert into public.quote_pricing (id, pricing, updated_at)
values ('main', '{
  "serviceLevels": [
    {"id":"essential","label":"Essential Planning","amount":3500},
    {"id":"signature","label":"Signature Experience","amount":8500},
    {"id":"royal","label":"Royal Full-Service","amount":16000}
  ],
  "decorLevels": [
    {"id":"light","label":"Light decor styling","amount":2500},
    {"id":"standard","label":"Standard decor styling","amount":6500},
    {"id":"luxury","label":"Luxury decor styling","amount":14000}
  ],
  "cateringOptions": [
    {"id":"none","label":"Not included","amount":0},
    {"id":"coordination","label":"Catering coordination only","amount":3000},
    {"id":"full","label":"Full catering support","amount":7500}
  ],
  "extras": [
    {"id":"travel","label":"Travel / logistics allowance","amount":1200,"enabled":true},
    {"id":"admin","label":"Admin & communication fee","amount":750,"enabled":true}
  ],
  "perGuestCoordination":45
}'::jsonb, now())
on conflict (id) do nothing;

insert into public.banking_details (id, banking, updated_at)
values ('main', '{
  "accountName":"",
  "bankName":"",
  "accountNumber":"",
  "accountType":"",
  "branchCode":"",
  "referenceFormat":"Use quotation reference as payment reference",
  "paymentNote":"Banking details are confirmed on the official quotation."
}'::jsonb, now())
on conflict (id) do nothing;

insert into public.site_settings (id, settings, updated_at)
values ('main', '{
  "name":"Events with Nick",
  "legal":"Events with Nick Pty (Ltd)",
  "registrationNumber":"",
  "vatNumber":"",
  "businessAddress":"Lephaphane Village, around Lephaphane Clinic, Tzaneen",
  "heroTitle":"Your Vision. Our Passion. Unforgettable Events.",
  "heroText":"Premium planning, decor styling and event coordination for weddings, corporate events, family celebrations and special occasions.",
  "aboutText":"Events with Nick creates polished event experiences with careful planning, elegant styling and professional coordination.",
  "slogan":"We do not just offer services; we help create memories and unite families.",
  "tagline":"Luxury event planning, decor and coordination",
  "location":"Tzaneen",
  "serviceArea":"Tzaneen, Limpopo and surrounding areas",
  "phone1":"076 186 4166",
  "phone2":"073 408 8417",
  "email":"mmolamn@gmail.com",
  "whatsapp":"0761864166",
  "facebook":"events_with_nicks",
  "instagram":"Events_with_nicks"
}'::jsonb, now())
on conflict (id) do nothing;

-- 8) Quick checks after running this SQL
-- A) Public bookings should save from the website.
-- B) Admin should log in with a Supabase Authentication user and immediately see rows in bookings.
-- C) Price Settings should save into quote_pricing.
